# Github action configuration runs functional test cases and generate artifact's 
# Author: Rahul Shukla <rahul.shukla@ilimi.in>


name: Sunbird-PDF-Player

# Trigger the workflow on push or pull request
on: [push, pull_request]
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies 
      run: |
        (npm install)

    - name: Build pdf player library
      run: |
        (ng build)

    - name: Package pdf player library 
      run: |
        (cd dist/pdf-player-v2 && npm pack)
    
    - name: Report artifact generation
      uses: actions/upload-artifact@v1
      with:
        name: Library generation
        path: dist/pdf-player-v2/pdf-player-v2-0.0.1.tgz

      env:
        CI: true
        
